### ISSUE TITLE
When using Chinese input method, the auto docking page automatically shrinks back.

### ISSUE THREAD

**Issue by zjjhot** [EnixCoda/Gitako#204] opened 2022-01-22 13:37 UTC
When using Chinese input method, 
when you enter text in the search text box , 
before the chararctor jump on the screen,
the auto docking page automatically shrinks back.

I'm using QQ input mehthod.

**Comment by EnixCoda** [comment] 2022-01-29 05:26
Hi @zjjhot Thanks for this issue!

I cannot reproduce this issue on Windows 10 + QQ IME. Could you provide more details?

**Comment by EnixCoda** [comment] 2022-03-27 14:48
Closing due to lack of info. We can reopen this when we get more input.

**Closed as completed by EnixCoda** 2022-03-27 14:48 UTC
