### ISSUE TITLE
Not working for gitea private repos

### ISSUE THREAD

**Issue by devbean** [EnixCoda/Gitako#275] opened 2023-01-04 02:57 UTC
Using Gitako with self-hosted gitea and private repos, Gitako icon flashes to disappear. Errors in console:
```
GET http://192.168.88.30:3080/api/v1/repos/meta/changelogs/git/trees/develop?recursive=1 403 (Forbidden)
Uncaught (in promise) Error: Only signed in user is allowed to call APIs.          content.js:74 
    at zr (content.js:74:117717)
```
There is no way to add access token because Gitako cannot even open as there is no icon on left side.

**Comment by EnixCoda** [comment] 2023-01-05 10:58
Thank you. Will fix it in `v3.10.1` soon.

**Comment by c-my** [comment] 2023-01-22 05:48
The sidebar shows `Access Denied` and I got this error in private repo even after setting access token:
```
GET https://{host}/api/v1/repos/{user_name}/{repo_name}/git/trees/master?recursive=1 404 content.js:74
```

This may be due to the absence of the field `authorization: token {access_token}` in the request header.

My gitea version is 1.18.1.

**Comment by EnixCoda** [comment] 2023-01-25 14:41
@devbean @c-my `v3.10.1` is under review. Please give another try tomorrow. Thank you!

**Comment by c-my** [comment] 2023-01-25 15:55
Thanks for the fix!

But still got 404 error and the sidebar shows "Access Denied".

![error](https://user-images.githubusercontent.com/22538534/214607882-f8bb0b27-e401-4292-8832-e349fe14fc78.png)

![access denied](https://user-images.githubusercontent.com/22538534/214609690-ce37451c-5071-4ef8-b3de-b9a3c3279871.png)


If I edit the failed request and add the `authorization: token {access_token}` in the headers, the request will success. 
The problem may come from here.

![error2](https://user-images.githubusercontent.com/22538534/214608968-1693ca11-0c65-4bca-8efd-d41b4f1d627f.png)

**Comment by EnixCoda** [comment] 2023-01-26 12:46
@c-my  Oh I misread `gitea` as `gitee`. And my fix was for another problem for gitee.

**Comment by EnixCoda** [comment] 2023-01-26 18:24
`v3.10.2` will be available tomorrow. The issue should be fixed this time.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/7480839/214918484-9a1867a9-a9e7-4e8f-a6c6-5936244d72d1.png">

**Comment by c-my** [comment] 2023-01-27 04:49
Thank you!
The problem is fixed.

**Closed as completed** 2023-01-27 05:13 UTC
Labels: bug
