### ISSUE TITLE
Cannot copy code from github pr file changed tab

### ISSUE THREAD

**Issue by cncolder** [EnixCoda/Gitako#125] opened 2021-03-05 04:36 UTC
After installing this extension. I cannot copy code from github pr `File changed` tab.

CMD+C or context menu.

Gitako v2.7.1

Recording: https://p-myf5wv.b3.n0.cdn.getcloudapp.com/items/wbu9qQee/8489acf7-cdfe-4456-9b63-357071cec5e6.gif

**Comment by kbsali** [comment] 2021-03-05 10:32
I can confirm the same issue on Brave (Chromium). It works correctly on Firefox however.

**Comment by EnixCoda** [comment] 2021-03-07 07:50
Thanks for this issue! I can confirm this in Chrome now.

Interesting. Gitako is not expected to block copying. I'll look into it later.

Hope it does not annoy you much :)

**Comment by EnixCoda** [comment] 2021-03-08 13:01
I have some new findings. This issue only happens when
1. Gitako is enabled
2. And the user has logged in to GitHub

And only happens when copy from elements within diff panels.

**Comment by EnixCoda** [comment] 2021-03-08 14:10
🤯

The issue is fixed after removing an unused CSS class in a0f6ad33987aefd24dd7df5e41894f97aed789c7 , `.invisible`, whose functionality is setting the element's `visibility` to `hidden`. The class was created since the very first few commits of Gitako at about **3 years ago** and soon deprecated. I forgot to removed it in time so that it was kept until today.

When `copy` event is triggered inside the diff panels, GitHub's script will append a new table element into DOM to sanitize the text to be copied. By coincidence, the element is of the exact same class name mentioned above, `invisible`.

![image](https://user-images.githubusercontent.com/7480839/110331255-dc377a00-8059-11eb-902b-53d5c9bc0045.png)

Thus the table element is not actually rendered, which is Chrome/Chromium's way of handling elements of `visibility: hidden` I guess, and the copy action fails.

What a bug.

**Comment by kbsali** [comment] 2021-03-08 15:14
Great news, I'll give it a new try on Chrome then (I switched back to octotree in the meantime! :)).
Thanks for the hard work and the follow up!

**Comment by EnixCoda** [comment] 2021-03-09 02:45
@kbsali I'll let you know when the next version is released :)

**Comment by EnixCoda** [comment] 2021-03-10 06:23
The patch has been released in `v2.7.2`.

cc @kbsali

**Closed as completed by EnixCoda** 2021-03-10 06:23 UTC

**Comment by kbsali** [comment] 2021-03-10 16:26
perfect, thanks!
