### ISSUE TITLE
Cannot navigate to file, automatically scrolls to top

### ISSUE THREAD

**Issue by R0boC0p** [EnixCoda/Gitako#163] opened 2021-07-23 09:33 UTC
It appears that when the PR is having a lot of files changes (in my case 104) the files on the bottom cannot be browsed. If you copy the link address, it gets apparent why:

copied link from the explorer:
working:
https://github.com/myRepo/pull/240/files#diff-9f17075dc63e2583beb0713d4c096fa23f9c81bee8f3f24c0609899ee5903d5d

not working:
https://github.com/myRepo/pull/240/files#

Files which cannot be loaded do appear to be
![image](https://user-images.githubusercontent.com/67147270/126763768-f72569f2-d8d5-4ccd-82a9-89a2b299b557.png)

but after loading the diff, the link still won't work.
Thanks in advance

**Comment by EnixCoda** [comment] 2021-07-26 06:37
@R0boC0p Thanks for submitting this issue!

Reproduced with #166

**Comment by EnixCoda** [comment] 2021-07-27 17:21
I found a solution, will ship it in the next patch release.

It is necessary to clarify that, as the PR should be quite large when this issue occurs and it takes much time to load the `files` tab content. So when trying to redirect to a file, which is at the bottom of the page, you might need to wait for quite a few seconds before the browser scroll to it. During the wait time, clicking or scrolling might prevent the expected redirect to the file to happen. This is not a bug as this behavior is aligned to GitHub's native behavior.

**Comment by EnixCoda** [comment] 2021-08-01 14:52
Fixed in `v3.3.0`, will release soon.

**Closed as completed by EnixCoda** 2021-08-01 14:52 UTC
Labels: bug
